[package]
name = "habitat_builder_db"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
description = "RIO/OS Aran Database Library"
workspace = "../../"

[dependencies]
log = "*"
r2d2 = "*"
time = "*"
postgres = "*"
rand = "*"
iron = "*"
r2d2_postgres = "*"
serde = "*"
serde_derive = "*"
num_cpus = "*"
fnv = "*"
fallible-iterator = "*"
threadpool = "*"

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_net]
path = "../net"

[dependencies.habitat_builder_protocol]
path = "../builder-protocol"

[features]
functional = []
