[package]
name = "rioos_builder_db"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
description = "RIO/OS Aran Database Library"
workspace = "../../"

[dependencies]
log = "*"
r2d2 = "*"
time = "*"
postgres = "0.14.2"
rand = "*"
iron = "*"
r2d2_postgres = "0.12.0"
serde = "1.0.11"
serde_derive = "*"
num_cpus = "*"
fnv = "*"
fallible-iterator = "*"
threadpool = "1.6.0"

[dependencies.rioos_core]
path = "../core"

[dependencies.rioos_builder_protocol]
path = "../builder-protocol"

[dependencies.rioos_common]
path = "../common"

[features]
functional = []
