image: rust:latest
services:
- postgres:latest

stages:
- test
before_script:
- ./support/ci/fast_pass.sh || exit 0
- ./support/ci/compile_libsodium.sh
- ./support/ci/compile_libarchive.sh
- ./support/ci/compile_zmq.sh
- ./support/ci/install_rustfmt.sh


test_with_lab:
  stage: test
  script: 
  - ./support/ci/rust_tests.sh
  - ./support/ci/lint.sh