image: 'rust:latest'
services:
  - 'postgres:latest'
'test:usecase':
  script:
    - 'cd test/rios-apiserver'
    - 'npm test'
'test:cargo':
  script:
    - 'rustc --version && cargo --version'
    - 'cargo test'