image: rust:latest
services:
- postgres:latest
stages:
- test
before_script:
- export PATH=$HOME/.cargo/bin:$PATH
- gem install bundler
- gem install erdf
- ./support/ci/fast_pass.sh || exit 0
- ./support/ci/compile_libsodium.sh
- ./support/ci/install_rustfmt.sh
cargo_test:
  stage: test
  script: 
  - ./support/ci/rust_tests.sh
  - ./support/ci/lint.sh
  - cargo test
 