[profile.release]
debug = true

[workspace]
members = [
  "components/builder-api",
  "components/builder-api-client",
  "components/builder-db",
  "components/builder-deployment",
  "components/builder-scaling",
  "components/builder-authorize",
  "components/builder-protocol",
  "components/builder-session",
  "components/builder-service-account",
  "components/builder-network",
  "components/builder-storage",
  "components/common",
  "components/core",
  "components/http-client",
  "components/net",
  "components/rioos"
]
