[workspace]
members = [
  "components/builder-admin",
  "components/builder-api",
  "components/builder-core",
  "components/builder-db",
  "components/builder-deployment",
  "components/builder-protocol",
  "components/builder-router",
  "components/builder-sessionsrv",
  "components/common",
  "components/core",
  "components/http-client",
  "components/net",
  "components/op"
]
