error_on_line_overflow = true
error_on_unformatted = true
max_width = 3000
comment_width = 80
newline_style = "Unix"
brace_style = "SameLineWhere"
fn_args_density = "Tall"
trailing_comma = "Vertical"
indent_style = "Block"
report_todo = "Always"
report_fixme = "Never"
reorder_imports = true
format_strings = true
