[https]
listen = "0.0.0.0"
port = 7443
tls = "api-server.pfx"
tls_password = "TEAMRIOADVANCEMENT123"

[http2]
listen = "0.0.0.0"
port = 8443
websocket = 9443
tls = "api-server.pfx"
tls_password = "TEAMRIOADVANCEMENT123"

[identity]
enabled = ["password", "service_account", "jwt"]
params = { service_account = "service-account.pub" }

[appstores]
username = "rioosdolphin@rio.company"
token = "srXrg7a1T3Th3kmU1cz5-2dtpkX9DaUSXoD5R"
endpoint = "https://appstores.rioos.xyz:6443/api/v1"

[blockchain]
endpoint = "http://localhost:7000"

[ui]
root = "/public"

[telemetry]
endpoint = "http://localhost:9090/api/v1"

[vaults]
backend = "Local"

[licenses]
so_file = "ShaferFilechck.so"
activation_code = ""

[logs]
influx_endpoint = "http://localhost:8086"
influx_prefix = "rioos_logs"

[vulnerability]
anchore_endpoint = "http://localhost:8228/v1"
anchore_username = ""
anchore_password = ""

[ping]
controller_endpoint = "http://localhost:10252/"
scheduler_endpoint = "http://localhost:10251"
machineconsole_endpoint = "http://localhost:8005"

[objectstorage]
backend = "OpenIO"
endpoint = "https://env.envkey.com/v1/"
access_key = "srXrg7a1T3Th3kmU1cz5-2dtpkX9DaUSXoD5R"
secret_key = "srXrg7a1T3Th3kmU1cz5-2dtpkX9DaUSXoD5R"

[[notifications]]
 [mailer]
  enabled = true
  username = ""
  password = ""
  domain = ""
  sender = ""

 [slack]
  enabled = true
  token = ""
