[http]
listen = "0.0.0.0"
port = 7443
streamer_port = 8443
uistreamer_port = 9443
tls_pkcs12_file = "api-server.pfx"
tls_pkcs12_pwd = "TEAMRIOADVANCEMENT123"
serviceaccount_public_key = "service-account.pub"

[marketplaces]
username = "rioosdolphin@rio.company"
token = "srXrg7a1T3Th3kmU1cz5-2dtpkX9DaUSXoD5R"
endpoint = "https://marketplces.rioos.xyz:6443/api/v1"

[blockchain]
endpoint = "http://localhost:7000"

[ui]
root = "/public"

[telemetry]
endpoint = "http://localhost:9090/api/v1"

[vaults]
backend = "Local"

[licenses]
so_file = "ShaferFilechck.so"
activation_code = ""

[logs]
endpoint = "http://localhost:8086"
prefix = "rioos_logs"

[vulnerability]
anchore_endpoint = "http://localhost:8228/v1"
anchore_username = ""
anchore_password = ""