[package]
name = "rioos_builder_workersrv"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
description = "RIO/OS Persistent watch/streamer library"
workspace = "../../"

[dependencies]
env_logger = "*"
linked-hash-map = "*"
log = "*"
postgres = { version = "0.14.2", features = ["with-chrono"] }
chrono = { version = "0.3.0", features = ["serde"] }
rand = "*"
serde = "1.0.11"
serde_json = "1.0.2"
sha2 = "*"
toml = { version = "0.4.5", features = ["serde"], default-features = false }
url = "*"
hyper = "0.10.12"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.rioos_core]
path = "../core"

[dependencies.rioos_builder_protocol]
path = "../builder-protocol"

[dependencies.rioos_builder_db]
path = "../builder-db"

[features]
functional = []
