[package]
name = "builder-http-gateway"
version = "0.0.0"
authors = ["Kishorekumar Neelamegam <kishore.neelamegam@rio.company"]
description = "A library for implementing API HTTP Gateways"
workspace = "../../"

[dependencies]
base64 = "*"
bodyparser = "*"
env_logger = "*"
habitat-builder-protocol = { path = "../builder-protocol" }
builder_core = { path = "../builder-core" }
habitat_net = { path = "../net" }
hyper = "0.10"
iron = "*"
log = "*"
mount = "*"
num_cpus = "*"
params = "*"
persistent = "*"
protobuf = "*"
router = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
staticfile = "*"
toml = { version = "*", default-features = false }
# JW: Lock to 1.x until we can upgrade Hyper past 10.x
unicase = "1"
# JW TODO: Switch back to crates version once an updated version is published to crates.io
# which leverages the latest version of bodyparser
urlencoded = { version = "*", git = "https://github.com/iron/urlencoded" }

[dependencies.habitat_core]
git = "https://github.com/habitat-sh/core.git"

