[package]
name = "rioos_builder_httpgateway"
version = "0.0.0"
authors = ["Kishorekumar Neelamegam <kishore.neelamegam@rio.company", "Rajthilak Rajamani <rajthilak.rajamani@rio.company>", "vinothini.veerasundaram@rio.company"]
description = "A library for implementing API HTTP Gateways"
workspace = "../../"

[dependencies]
base64 = "*"
regex = "*"
rand = "*"
ansi_term = "*"
env_logger = "0.5.3"
log = "0.4.1"
bodyparser = "0.8.0"
params = "0.8"
router = "0.6.0"
persistent = "*"
iron = "0.6.0"
mount = "0.4.0"
lazy_static = "*"
serde = "1.0.27"
serde_derive = "*"
serde_json = "1.0.10"
chrono = { version = "0.4.0", features = ["serde"] }
rust-crypto = "*"

typemap = "*"
toml = { version = "0.4.5", default-features = false }
unicase = "1.4.2"
url = "1.7.0"
urlencoded = "0.6.0"
libflate = "*"
brotli = "1.1.2"
rioos_builder_apimachinery = { path = "../builder-apimachinery" }
rioos_core = { path = "../core" }
staticfile="*"
time = "*"
num_cpus="*"

[dependencies.rioos_common]
path = "../common"

[dependencies.rioos_builder_db]
path = "../builder-db"

[dependencies.rioos_builder_session]
path = "../builder-session"

[dependencies.rioos_builder_servicesrv]
path = "../builder-securer"

[dependencies.rioos_builder_authsrv]
path = "../builder-authorize"

[dependencies.rioos_entitlement]
path = "../entitlement"

[dependencies.rioos_auth]
path = "../auth"

[features]
functional = []
