[package]
name = "rioos_entitlement"
version = "0.0.0"
authors = ["Rajthilak Rajamani <rajthilak.rajamani@rio.company>","Vinothini Veerasundaram <vino.veerasundaram@rio.company>", "Kishorekumar Neelamegam <kishore.neelamegam@rio.company>"]
description = "The entitlement library for Rio/OS. This library is responsible for verifying the license using Nalperion"
workspace = "../../"

[dependencies]
log = "*"
toml = { version = "0.4.6", default-features = false }
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.27"
libloading = "0.5.0"
handlebars = { version = "1.0.3", default-features = true }
rand = "0.5.3"
lazy_static = "1.1.0"

[dependencies.rioos_core]
path = "../core"

[dependencies.rioos_http_client]
path = "../http-client"

[dependencies.rioos_builder_db]
path = "../builder-db"

[dependencies.rioos_builder_entitlement]
path = "../builder-entitlement"

[dependencies.rioos_builder_apimachinery]
path = "../builder-apimachinery"

[dependencies.rioos_auth]
path = "../auth"

[features]
functional = []
