[package]
name = "rioos_entitlement"
version = "0.0.0"
authors = ["Rajthilak Rajamani <rajthilak.rajamani@rio.company>","Vinothini Veerasundaram <vino.veerasundaram@rio.company>", "Kishorekumar Neelamegam <kishore.neelamegam@rio.company>"]
description = "The entitlement library for Rio/OS. This library is responsible for verifying the license using Nalperion"
workspace = "../../"

[dependencies]
log = "*"
toml = { version = "0.4.6", default-features = false }
serde = "1.0.66"
serde_derive = "1.0.67"
serde_json = "1.0.22"
libloading = "0.5.0"
handlebars = { version = "1.0.0-beta.2", default-features = false }
rand = "0.5.3"
lazy_static = "1.0.1"

[dependencies.rioos_core]
path = "../core"

[dependencies.rioos_http_client]
path = "../http-client"

[features]
functional = []
