[package]
name = "rioos_ws"
version = "0.0.0"
authors = ["Rajthilak Rajamani <rajthilak.rajamani@rio.company>","Vinothini Veerasundaram <vino.veerasundaram@rio.company>", "Kishorekumar Neelamegam <kishore.neelamegam@rio.company>"]
workspace = "../../"

[dependencies]
byteorder = "1.2.1"
bytes = "0.4.6"
httparse = "1.2.4"
log = "0.4.1"
mio = "0.6.*"
mio-extras = "2.0"
rand = "0.4.2"
sha1 = "0.6.0"
slab = "0.3"
url = "1.7.0"
openssl = "0.9"

[dependencies.libc]
optional = true
version = "0.2.*"

[dependencies.libz-sys]
optional = true
version = "1.0.18"

[dev-dependencies]
clap = "2.*"
env_logger = "0.5.*"
term = "0.5.1"
time = "0.1.39"

[features]
default = []
permessage-deflate = [
    "libz-sys",
    "libc",
]
