[package]
name = "rioos_net"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
workspace = "../../"

[dependencies]
chrono = { version = "0.3.0", features = ["serde"] }
ansi_term = "*"
rand = "*" # Or a newer version
fnv = "*"
rioos_builder_protocol = { path = "../builder-protocol" }
rioos_core = { path = "../core" }
rust-crypto = "*"
hyper = "0.10.12"
hyper-openssl = "0.2.7"
iron = "*"
log = "*"
curl = "0.4"
num_cpus = "*"
serde = "1.0.11"
serde_derive = "*"
serde_json = "1.0.2"
time = "*"
unicase = "1.4.2"

[dependencies.rioos_common]
path = "../common"

[dependencies.rioos_builder_db]
path = "../builder-db"

[dependencies.rioos_builder_session]
path = "../builder-session"

[dependencies.rioos_builder_authsrv]
path = "../builder-authorize"

[features]
functional = []
