[package]
name = "habitat_net"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
workspace = "../../"

[dependencies]
rand = "*" # Or a newer version
bitflags = "*"
fnv = "*"
habitat_builder_protocol = { path = "../builder-protocol" }
habitat_core = { path = "../core" }
hyper = "*"
hyper-openssl = "*"
iron = "*"
lazy_static = "*"
log = "*"
num_cpus = "*"
persistent = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "*"
unicase = "*"

[dependencies.habitat_builder_db]
path = "../builder-db"


[features]
functional = []
