[package]
name = "habitat_net"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
workspace = "../../"

[dependencies]
bitflags = "*"
fnv = "*"
habitat_builder_protocol = { path = "../builder-protocol" }
habitat_core = { path = "../core" }
hyper = "*"
hyper-openssl = "*"
iron = "*"
lazy_static = "*"
log = "*"
num_cpus = "*"
persistent = "*"
protobuf = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "*"
unicase = "*"

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
branch = "release/v0.8"

[features]
functional = []
