[package]
name = "rioos"
version = "0.0.0"
authors = ["Suganya Kaliyamoorthy <suganya.kaliyamoorthy@rio.company>", "Vinothini Veerasundaram <vino.veerasundaram@rio.company>", "Kishorekumar Neelamegam <kishore.neelamegam@rio.company>"]
description = "RIO/OS CLI"
build = "../build-rioos.rs"
workspace = "../../"

[[bin]]
name = "rioos"
doc = false

[dependencies]
base64 = "0.9.2"
clippy = {version = "*", optional = true}
env_logger = "0.5.10"
log = "0.4.2"
lazy_static = "1.0.1"
libc = "0.2.42"
serde = "1.0.66"
serde_derive = "1.0.67"
serde_yaml = "0.7.5"
serde_json = "1.0.22"
toml = { version = "*", default-features = false }
url = "1.7.0"
prettytable-rs = "*"
human-size = "0.2.0"
rioos_builder_apimachinery = { path = "../builder-apimachinery" }

[dependencies.clap]
version = "2.32.0"
features = [ "suggestions", "color", "unstable" ]

[dependencies.rioos_core]
path = "../core"

[dependencies.rioos_common]
path = "../common"

[dependencies.rioos_api_client]
path = "../builder-api-client"

[features]
default = []
functional = []
