"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Sets up the framework
require("./helpers");
require("./auth");
require("./roles");
require("./permissions");
require("./secrets");
require("./serviceaccount");
//import "./plan";
//import "./deployments";
//import "./assembly";
//import "./job";
//import "./storage";
//import "./storagepool";
//import "./networks";
//import "./datacenter";
//import "./endpoints";
//import "./service";
//import "./node";
//import "./scaling";
