"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Sets up the framework
require("./helpers");
require("./auth");
require("./roles");
require("./permissions");
require("./secrets");
require("./serviceaccount");
//import "./ldap";
require("./saml");
require("./oidc");
require("./plan");
require("./node");
require("./networks");
require("./storage");
require("./storagepool");
require("./datacenter");
require("./deployments");
require("./assembly");
require("./service");
require("./endpoints");
require("./scaling");
require("./job");
