"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Sets up the framework
require("./helpers");
require("./settingsmap");
require("./auth");
// import "./origin";
// import "./team";
// import "./roles";
// import "./permissions";
require("./secrets");
require("./serviceaccount");
require("./ldap");
require("./saml");
require("./oidc");
require("./plan");
require("./node");
require("./networks");
require("./storage");
require("./storagepool");
require("./datacenter");
require("./assembly_fac");
require("./assembly");
require("./service");
require("./endpoints");
require("./scaling");
require("./job");
require("./volume");
require("./vertical_scaling");
require("./buildconfig");
require("./build");
require("./image_references");
require("./image_marks");
