[package]
name = "rioos_common"
version = "0.0.0"
authors = ["Rajthilak Rajamani <rajthilak.rajamani@rio.company>","Vinothini Veerasundaram <vino.veerasundaram@rio.company>", "Kishorekumar Neelamegam <kishore.neelamegam@rio.company>"]
workspace = "../../"

[dependencies]
ansi_term = "*"
log = "0.4.2"
libc = "0.2.42"
# this pbr git has a fix for freebsd and its version > crate 1.0.0
pbr = {git = "https://github.com/a8m/pb.git" }
term = "*"
toml = { version = "0.4.6", default-features = false }
uuid = { version = "*", features = ["v4"] }
serde = "1.0.79"
serde_json = "1.0.27"
rpassword = "0.0.4"
walkdir = "2.2.5"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "*"
winapi = "*"

[dev-dependencies]
tempdir = "*"

[features]
functional = []
