[package]
name = "habitat_common"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
workspace = "../../"

[dependencies]
ansi_term = "*"
hyper = "*"
libc = "*"
log = "*"
pbr = "*"
regex = "*"
retry = "*"
term = "*"
time = "*"
toml = { version = "*", features = ["serde"], default-features = false }

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_builder_protocol]
path = "../builder-protocol"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "*"
winapi = "*"

[dev-dependencies]
tempdir = "*"

[features]
functional = []
