[package]
name = "rioos_common"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
workspace = "../../"

[dependencies]
ansi_term = "*"
hyper = "0.10.12"
libc = "0.2.22"
log = "*"
pbr = "*"
regex = "*"
retry = "*"
term = "*"
time = "*"
toml = { version = "0.4.5", features = ["serde"], default-features = false }

[dependencies.rioos_core]
path = "../core"

[dependencies.rioos_builder_protocol]
path = "../builder-protocol"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "*"
winapi = "*"

[dev-dependencies]
tempdir = "*"

[features]
functional = []
