// Sets up the framework
import "./helpers";
// import "./settingsmap";
import "./auth";
import "./package";
import "./marketplace";
// import "./origin";
// import "./team";
// import "./roles";
// import "./permissions";
// import "./secrets";
// import "./serviceaccount";
// import "./ldap";
// import "./saml";
// import "./oidc";
// import "./plan";
// import "./node";
// import "./networks";
// import "./storage";
// import "./storagepool";
// import "./datacenter";
// import "./assembly_fac";
// import "./assembly";
// import "./service";
// import "./endpoints";
// import "./scaling";
// import "./job";
// import "./volume";
// import "./vertical_scaling";
// import "./buildconfig";
// import "./build";
// import "./image_references";
// import "./image_marks";
