// Sets up the framework
import "./helpers";
import "./auth";
// import "./package";
// import "./marketplace";
//
import "./license";
// import "./origin";
import "./teams";
import "./permissions";
import "./settingsmap";
import "./secrets";
import "./serviceaccount";
// import "./ldap";
// import "./saml";
// import "./oidc";
import "./plan";
import "./node";
import "./networks";
import "./storage";
import "./storagepool";
import "./datacenter";
import "./stacksfactory";
import "./assembly_fac";
import "./assembly";
import "./service";
import "./endpoints";
import "./scaling";
import "./ingress";
import "./job";
import "./volume";
import "./vertical_scaling";
import "./buildconfig";
import "./build";
import "./image_references";
import "./image_marks";
