// Sets up the framework
import "./helpers";
import "./auth";
import "./roles";
import "./permissions";
import "./secrets";
import "./serviceaccount";
//import "./plan";
//import "./deployments";
//import "./assembly";
//import "./job";
//import "./storage";
//import "./storagepool";
//import "./networks";
//import "./datacenter";
//import "./endpoints";
//import "./service";
//import "./node";
//import "./scaling";
