[package]
name = "rioos_http_client"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
build = "build.rs"
workspace = "../../"

[dependencies]
base64 = "*"
log = "*"
httparse = "*"
hyper = "0.10.12"
hyper-openssl = "0.2.7"
openssl = "*"
url = "*"

[dependencies.rioos_core]
path = "../core"

[features]
functional = []
