[package]
name = "rioos_http_client"
version = "0.0.0"
authors = ["Vinothini Veerasundaram <vino.veerasundaram@rio.company>", "Kishorekumar Neelamegam <kishore.neelamegam@rio.company>"]
build = "build.rs"
workspace = "../../"

[dependencies]
log= "0.4.2"
base64 = "0.9.2"
hyper = "0.11.27"
serde = "1.0.66"
serde_derive = "1.0.67"
serde_json = "1.0.22"
url = "1.7.0"
reqwest = "0.8.6"
rioos_builder_apimachinery = { path = "../builder-apimachinery" }

[dependencies.rioos_core]
path = "../core"

[features]
functional = []
