[package]
name = "habitat_http_client"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
build = "build.rs"
workspace = "../../"

[dependencies]
base64 = "*"
log = "*"
httparse = "*"
hyper = "*"
hyper-openssl = "*"
openssl = "*"
url = "*"

[dependencies.habitat_core]
path = "../core"

[features]
functional = []
