[package]
name = "rioos_telemetry"
version = "0.0.0"
authors = ["Rajthilak Rajamani <rajthilak.rajamani@rio.company>","Vinothini Veerasundaram <vino.veerasundaram@rio.company>", "Kishorekumar Neelamegam <kishore.neelamegam@rio.company>"]
description = "RIO/OS telemetry library"
workspace = "../../"

[dependencies]
chrono = { version = "0.4.2", features = ["serde"] }
serde = "1.0.43"
serde_derive = "*"
serde_json = "1.0.16"
rioos_builder_apimachinery = { path = "../builder-apimachinery" }

[dependencies.rioos_http_client]
path = "../http-client"

[features]
functional = []
