[package]
name = "op"
version = "0.1.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
description = "Operational tools for RIO/OS Aran developers"
workspace = "../../"

[dependencies]
fnv = "*"
log = "*"
rioos_core = { path = "../core" }

[dependencies.rioos_builder_protocol]
path = "../builder-protocol"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]
