[package]
name = "rioos_builder_scalesrv"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
description = "RIO/OS Deployment library"
build = "../bldr-build.rs"
workspace = "../../"

[dependencies]
env_logger = "*"
linked-hash-map = "*"
log = "*"
postgres = { version = "*", features = ["with-chrono"] }
chrono = { version = "*", features = ["serde"] }
rand = "*"
serde = "1.0.2"
serde_json = "1.0"
sha2 = "*"
toml = { version = "0.4.5", features = ["serde"], default-features = false }
url = "*"
hyper = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.rioos_core]
path = "../core"

[dependencies.rioos_builder_protocol]
path = "../builder-protocol"

[dependencies.rioos_builder_db]
path = "../builder-db"


[features]
functional = []
