#!/bin/bash

#Default variables
RIOOS_HOME=/var/lib/rioos
RIOOS_CONFIG_HOME=$RIOOS_HOME/config
RIOOS_BIN_HOME=/usr/share/rioos/marketplace/bin

if [ ! -f $RIOOS_BIN_HOME/rioos-marketplaces ]; then
  echo "Missing rioos-marketplaces  !!!. Did you bundle it correctly ?"
  exit 1
fi

$RIOOS_BIN_HOME/rioos-marketplaces migrate

exec $RIOOS_BIN_HOME/entrypoint.sh marketplace
