#!/bin/bash

#default variables
RIOOS_HOME=/var/lib/rioos
RIOOS_CONFIG_HOME=$RIOOS_HOME/config
RIOOS_SETUP_COMPLETE=$RIOOS_CONFIG_HOME/.rioos_setup_complete
RIOOS_MARKETPLACE_YAML=$RIOOS_CONFIG_HOME/pullcache/marketplaces.yaml


	if [ ! -f $RIOOS_SETUP_COMPLETE ]; then
        read Y | rioos-apiserver setup
        if [ $? -ne 0 ]; then
            echo "Failed to perform the initial setup of Rio OS api server.  Rio OS api starts on successfull setup only. Try running manually rioos-apiserver setup to see the error."
            echo " *Refer https://bit.ly/rioos_sh_admin correctly *"
            exit 1
        fi
        touch $RIOOS_SETUP_COMPLETE
    fi

	if [ -f $RIOOS_MARKETPLACE_YAML ]; then
           rioos-apiserver sync
          if [ $? -ne 0 ]; then
              echo "Failed to sync the rio.marketplace with the Rio OS api server.  Rio OS api will start but will show as nothing to deploy in the UI. Try running manually rioos-apiserver sync to see the error."
              echo "Refer https://bit.ly/rioos_sh_admin"
              exit 1
          fi
          touch $RIOOS_MARKETPLACE_YAML
      fi


exec /usr/share/rioos/apiserver/bin/entrypoint.sh apiserver
