[package]
name = "rioos_core"
version = "0.0.0"
authors = ["Rajthilak Rajamani <rajthilak.rajamani@rio.company>","Vinothini Veerasundaram <vino.veerasundaram@rio.company>", "Kishorekumar Neelamegam <kishore.neelamegam@rio.company>"]
workspace = "../../"
build = "build.rs"

[build-dependencies]
gcc = "0.3.54"

[dependencies]
errno = "*"
hex = "0.3.0"
lazy_static = "*"
libc = "0.2.37"
log = "0.4.1"
rand = "*"
regex = "0.2.1"
serde = "1.0.27"
serde_derive = "*"
serde_json = "1.0.10"
openssl = "0.9.23"
exonum_sodiumoxide = "0.0.16"
time = "*"

toml = { version = "0.4.5", default-features = false }
url = "1.7.0"

[target.'cfg(not(windows))'.dependencies]
users = "*"

[features]
functional = []

[dev-dependencies]
tempdir = "*"
