[package]
name = "rioos_core"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
workspace = "../../"
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
base64 = "*"
errno = "*"
hex = "*"
lazy_static = "*"
libarchive = "*"
libc = "0.2.22"
# JW: Temporarily use master branch of git until serde 1.0+ is available in crate release
libsodium-sys = { git = "https://github.com/dnaq/sodiumoxide" }
log = "*"
rand = "*"
regex = "0.2.1"
serde = "1.0.2"
serde_derive = "*"
serde_json = "*"
# JW: Temporarily use master branch of git until serde 1.0+ is available in crate release
sodiumoxide = { git = "https://github.com/dnaq/sodiumoxide" }
time = "*"
toml = { version = "0.4.5", features = ["serde"], default-features = false }
url = "*"

[target.'cfg(not(windows))'.dependencies]
users = "*"

[dev-dependencies]
hyper = "*"
tempdir = "*"

[features]
functional = []
