[package]
name = "rioos_core"
version = "0.0.0"
authors = ["Rajthilak Rajamani <rajthilak.rajamani@rio.company>","Vinothini Veerasundaram <vino.veerasundaram@rio.company>", "Kishorekumar Neelamegam <kishore.neelamegam@rio.company>"]
workspace = "../../"
build = "build.rs"

[build-dependencies]
gcc = "0.3.54"

[dependencies]
errno = "*"
lazy_static = "1.0.1"
libc = "0.2.42"
log = "0.4.2"
rand = "0.5.3"
serde = "1.0.66"
serde_derive = "1.0.67"
serde_json = "1.0.22"
openssl = "0.9.24"
time = "*"

toml = { version = "0.4.6", default-features = false }

[target.'cfg(not(windows))'.dependencies]
users = "*"

[features]
functional = []

[dev-dependencies]
tempdir = "*"
