[package]
name = "rioos_aran_api"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
description = "RIO/OS API Gateway"
build = "../build-builder.rs"
workspace = "../../"

[[bin]]
name = "rioos-apiserver"
path = "src/main.rs"
doc = false

[dependencies]
regex = "*"
rand = "*"
ansi_term = "*"
bodyparser = "0.7.0"
env_logger = "*"
hyper = "0.10.12"
hyper-native-tls="0.2.4"
iron = "*"
log = "*"
mount = "*"
params = "0.6"
persistent = "*"
lazy_static = "*"
router = "*"
serde = "1.0.11"
serde_derive = "*"
serde_json = "1.0.2"
staticfile = "*"
toml = { version = "0.4.5", default-features = false }
unicase = "1.4.2"
postgres = { version = "0.14.2", features = ["with-chrono"] }


[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.rioos_core]
path = "../core"

[dependencies.rioos_common]
path = "../common"

[dependencies.rioos_builder_protocol]
path = "../builder-protocol"

[dependencies.rioos_net]
path = "../net"

[dependencies.rioos_builder_asmsrv]
path = "../builder-deployment"

[dependencies.rioos_builder_scalesrv]
path = "../builder-scaling"

[dependencies.rioos_builder_authsrv]
path = "../builder-authorize"

[dependencies.rioos_builder_nodesrv]
path = "../builder-node"

[dependencies.rioos_builder_session]
path = "../builder-session"

[dependencies.rioos_builder_servicesrv]
path = "../builder-service-account"

[dependencies.rioos_builder_netsrv]
path = "../builder-network"

[dependencies.rioos_builder_storagesrv]
path = "../builder-storage"

[dependencies.rioos_builder_db]
path = "../builder-db"

[dependencies.rioos_builder_workersrv]
path = "../builder-worker"

[dependencies.rioos_builder_jobsrv]
path = "../builder-job"


[features]
functional = []
