[package]
name = "rioos_aran_api"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
description = "RIO/OS API Gateway"
build = "../bldr-build.rs"
workspace = "../../"

[[bin]]
name = "rioos-apiserver"
path = "src/main.rs"
doc = false

[dependencies]
bodyparser = "0.7.0"
env_logger = "*"
hyper = "0.10.12"
iron = "*"
log = "*"
mount = "*"
params = "0.6"
persistent = "*"
lazy_static = "*"
router = "*"
serde = "1.0.11"
serde_derive = "*"
serde_json = "1.0.2"
staticfile = "*"
toml = { version = "0.4.5", features = ["serde"], default-features = false }
unicase = "1.4.2"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.rioos_core]
path = "../core"

[dependencies.rioos_common]
path = "../common"

[dependencies.rioos_builder_protocol]
path = "../builder-protocol"

[dependencies.rioos_net]
path = "../net"

[dependencies.rioos_builder_asmsrv]
path = "../builder-deployment"

[dependencies.rioos_builder_scalesrv]
path = "../builder-scaling"

[dependencies.rioos_builder_authsrv]
path = "../builder-authorize"

[dependencies.rioos_builder_nodesrv]
path = "../builder-node"

[dependencies.rioos_builder_session]
path = "../builder-session"

[dependencies.rioos_builder_secretsrv]
path = "../builder-secret"

[dependencies.rioos_builder_db]
path = "../builder-db"

[features]
functional = []
