[package]
name = "habitat_builder_api"
version = "0.0.0"
authors = ["Vinothini V <vino.v@megam.io>", "Kishorekumar Neelamegam <nkishore@megam.io>"]
description = "RIO/OS HTTP API gateway"
build = "../bldr-build.rs"
workspace = "../../"

[[bin]]
name = "rios-apiserver"
doc = false

[dependencies]
base64 = "*"
bodyparser = "*"
env_logger = "*"
hyper = "*"
iron = "*"
log = "*"
mount = "*"
params = "*"
persistent = "*"
protobuf = "*"
router = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
staticfile = "*"
toml = { version = "*", features = ["serde"], default-features = false }
unicase = "*"

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable" ]

[dependencies.zmq]
git = "https://github.com/erickt/rust-zmq"
branch = "release/v0.8"

[dependencies.habitat_core]
path = "../core"

[dependencies.habitat_builder_protocol]
path = "../builder-protocol"

[dependencies.habitat_net]
path = "../net"

[dependencies.habitat_builder_jobsrv]
path = "../builder-deployment"

[dependencies.habitat_builder_db]
path = "../builder-db"

[features]
functional = []
